### ISSUE TITLE
The 'nice' initial camera position is breaking

### ISSUE THREAD

**Issue by siddhartpai** [bwasty/gltf-viewer#18]
The 'nice' initial camera seems to be working for the 'Damaged Helmet' model perfectly but seems to be breaking for other models such as the one attached to this issue . 
The attached model exits with a panic . I've also attached the panic error message . 

GLTF File : https://transfer.sh/mWi4F/lighter.zip

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VBoxCutFailed', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: gltf_viewer::viewer::GltfViewer::screenshot
             at src/viewer.rs:326
  12: gltf_viewer::viewer::GltfViewer::multiscreenshot
             at src/viewer.rs:345
  13: gltf_viewer::main
             at src/main.rs:108
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  15: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: _start
`

**Comment by bwasty** [comment]
I can't reproduce it - the screenshots look bad, but there's no panic. I've used this 
```CARGO_INCREMENTAL=1 cargo run -- target/lighter/scene.gltf -vv -s target/lighter.png -c 3``` (macOS)

What line is it failing on? The line numbers in your message don't seem to match `master`.

**Comment by siddhartpai** [comment]
I'm sorry , seems like it's failing on my branch , sorry about the confusion. But is there someway the screenshots could be made proper ?

**Comment by bwasty** [comment]
Hmm, it renders much better on [gltf-viewer.donmccurdy.com](https://gltf-viewer.donmccurdy.com/), so it shouldn't be too hard to fix I hope (the camera positioning is based on Don McCurdy's code).

**Comment by bwasty** [comment]
I haven't looked into fixing the auto camera positioning yet, but there are now some CLI parameters for the camera: #20.

**Comment by bwasty** [comment]
This should fix it:  #21. The lighter looks much better, so do (almost) all sample models (-> [load_all_samples.sh](https://github.com/bwasty/gltf-viewer/blob/master/tests/load_all_samples.sh))
