### ISSUE TITLE
Light Implementation

### ISSUE THREAD

**Issue by siddhartpai** [bwasty/gltf-viewer#19]
Hi @bwasty 

It seems like currently point lights are applied somehow on the object so that it is shown on the screen and lit up . 
Is there someway i can change the point light implementation to an ambient light ?

**Comment by bwasty** [comment]
It's actually a single directional light at the moment. For better lighting we could either add an ambient lighting term to the shader or use IBL. Here's the reference shader demo where you can play a bit with the lighting: http://github.khronos.org/glTF-WebGL-PBR/
The current lighting should be equivalent to a `lightScale` of 5 (-> see [here](https://github.com/bwasty/gltf-viewer/blob/master/src/shader.rs#L308))  and IBL contribution of 0.

For IBL we'd only need to add support for loading diffuse and specular [environment maps](https://github.com/KhronosGroup/glTF-WebGL-PBR#environment-maps), the shader already supports it (-> see [here](https://github.com/bwasty/gltf-viewer/blob/master/src/shaders/pbr-frag.glsl#L137-L164)).

Adding a constant ambient term should also be pretty easy, but I'm not sure where exactly in the shader to add it - my previous attempts didn't look good enough. Perhaps [this](https://learnopengl.com/PBR/Lighting) might help. Essentially it should look somewhat like this:
```
uniform float u_AmbientIntensity;
...
color += u_AmbientIntensity * baseColor * ao;

**Comment by alteous** [comment]
FYI, a lights extension is being discussed: https://github.com/KhronosGroup/glTF/issues/945

**Comment by bwasty** [comment]
@alteous Thanks, I'm aware of it. Was also thinking of adding it.

**Comment by bwasty** [comment]
@siddhartpai 
I've added simple ambient lighting: https://github.com/bwasty/gltf-viewer/commit/dbdd01c73fad1c15d8eccb26009e53d85ee09ac1. 
Here are some before and after screenshots of the official sample models:
https://bwasty.github.io/gltf-viewer/no_ambient/
https://bwasty.github.io/gltf-viewer/ambient_0.2/

The ambient light color and intensity can be adjusted in `shader.rs` (uniforms `u_AmbientLightColor `, `u_AmbientLightIntensity`).
