### ISSUE TITLE
some gltf model cannot be rendered perfectly 

### ISSUE THREAD

**Issue by piaoger** [bwasty/gltf-viewer#30]
I have some gltf models converted from OBJ with Cesium online obj2gltf tool.  

Cesium Obj2gltf converter : [link](http://52.4.31.236/convertmodel.html)

gltf model : [model.gltf.zip](https://github.com/bwasty/gltf-viewer/files/1828461/model.gltf.zip)

![gltf-viewer](https://user-images.githubusercontent.com/179429/37641306-30f58c10-2c54-11e8-8c60-8b1be330192f.gif)
 
![gltfviewer-webgl](https://user-images.githubusercontent.com/179429/37644487-f6aa1e94-2c5e-11e8-92e8-9dfe3ca4808d.gif)

**Comment by bwasty** [comment]
Looks like the object is very big and the far plane is to 'near'. I meant to adjust it based on the bounding box like in Don McCurdy's viewer but skipped it since it was fine for all sample models. Will add it now after all... (probably on Friday).
