### ISSUE TITLE
first two bytes is not a SOI marker

### ISSUE THREAD

**Issue by siddhartpai** [bwasty/gltf-viewer#39]
Hi @bwasty 

The gltf-viewer is breaking for a model with the following error. The model loads up fine on gltf-viewer.donmccurdy.com

The model in question is available at this url : https://assets.scapic.com/scapicAssets/Objects/6y478g7qqjfvl72am_6y478g7qqjftt22zq_Dragon.zip

I've attached the error below : 
`[WARN] Ignoring further joint attributes, only supporting JOINTS_0. (mesh: 0, primitive: 0)
[WARN] Ignoring further weight attributes, only supporting WEIGHTS_0. (mesh: 0, primitive: 0)
thread 'main' panicked at 'Image loading failed.: FormatError("first two bytes is not a SOI marker")', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:799
  11: gltf_viewer::render::texture::Texture::from_gltf
             at src/render/texture.rs:92
  12: gltf_viewer::render::material::load_texture
             at src/render/material.rs:132
  13: gltf_viewer::render::material::Material::from_gltf
             at src/render/material.rs:85
  14: gltf_viewer::render::primitive::Primitive::from_gltf
             at src/render/primitive.rs:212
  15: gltf_viewer::render::mesh::Mesh::from_gltf::{{closure}}
             at src/render/mesh.rs:32
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  17: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:398
  18: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1251
  19: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1800
  20: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1713
  21: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1300
  22: gltf_viewer::render::mesh::Mesh::from_gltf
             at src/render/mesh.rs:29
  23: gltf_viewer::render::node::Node::from_gltf
             at src/render/node.rs:57
  24: gltf_viewer::render::root::Root::from_gltf::{{closure}}
             at src/render/root.rs:29
  25: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at /checkout/src/libcore/ops/function.rs:271
  26: <core::option::Option<T>>::map
             at /checkout/src/libcore/option.rs:398
  27: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next
             at /checkout/src/libcore/iter/mod.rs:1251
  28: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter
             at /checkout/src/liballoc/vec.rs:1800
  29: <alloc::vec::Vec<T> as core::iter::traits::FromIterator<T>>::from_iter
             at /checkout/src/liballoc/vec.rs:1713
  30: core::iter::iterator::Iterator::collect
             at /checkout/src/libcore/iter/iterator.rs:1300
  31: gltf_viewer::render::root::Root::from_gltf
             at src/render/root.rs:28
  32: gltf_viewer::viewer::GltfViewer::load
             at src/viewer.rs:252
  33: gltf_viewer::viewer::GltfViewer::new
             at src/viewer.rs:167
  34: gltf_viewer::main
             at src/main.rs:144
  35: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  36: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  37: main
  38: __libc_start_main
  39: _start
`

**Comment by bwasty** [comment]
Sorry for the late reply - the error comes from the `image` crate:
https://github.com/bwasty/gltf-viewer/blob/f74fb58cff84d34665c205e6aee58f03e7ad7a72/src/render/texture.rs#L92

Not sure what to do about it - either the `image` crate has a bug, or the the file is invalid, but most other loaders ignore it.
