### ISSUE TITLE
google draco support

### ISSUE THREAD

**Issue by tomuxmon** [bwasty/gltf-viewer#46]
Any plans to support KHR_draco_mesh_compression? Currently, I get an error when trying to view any draco compressed sample:

PS C:\sc\git\glTF-Sample-Models\2.0\Box\glTF-Draco> gltf-viewer.exe Box.gltf
[ERROR] glTF import failed: Gltf(Deserialize(ErrorImpl { code: Message("missing field `bufferView`"), line: 78, column: 5 }))

**Comment by bwasty** [comment]
That error comes from the [gltf](https://github.com/gltf-rs/gltf) crate and should probably be filed there. As far as I know, draco compressed meshes should always an uncompressed fallback and load anyway.
Proper decompression support would also better fit in the `gltf` crate I think.

**Comment by bwasty** [comment]
See https://github.com/gltf-rs/gltf/issues/242.

**Comment by alteous** [comment]
> As far as I know, draco compressed meshes should always an uncompressed fallback and load anyway.

Not if `KHR_draco_mesh_compression` is listed under `extensionsRequired`. In that case the uncompressed data may be omitted. There wouldn't be much point in the extension if you had to supply both uncompressed and compressed data!
