### ISSUE TITLE
cannot open gltf

### ISSUE THREAD

**Issue by piaoger** [bwasty/gltf-viewer#5]
how to repo:
 - download the sample gltf to project root
 - cargo run -- release ./BarramundiFish.gltf 
 - import error found

More details
```
piaoger$ cargo run --release ./BarramundiFish.gltf 
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/gltf-viewer ./BarramundiFish.gltf`
[ERROR] glTF import failed: I/O error
```
gltf viewer in rust is interesting! please let me know if I missed anything. Thanks.

**Comment by bwasty** [comment]
Did you also download all the related files (.bin and .png)? The error can also occur for files with "embedded" resources as the `gltf` crate temporarily removed data URI handling.

I also just pushed a commit re-activating the "simple" shader (I'm in the middle of integrating PBR, but it's not done yet, so nothing was rendered).

**Comment by piaoger** [comment]
Thanks for your feedback. I downloaded gltf file including textures to local and  found it works fine in latest version. You are right 👍
