### ISSUE TITLE
Misuse of MaybeUninit

### ISSUE THREAD

**Issue by Lokathor** [bwasty/gltf-viewer#63]
https://github.com/bwasty/gltf-viewer/commit/09c8d582970c33f2e9af3e5c032cb7febb07f3aa#diff-3dbd16223f25e8b5e0bcf099743107e9R120

This replaced

```rust
mem::uninitialized()
```

with

```rust
mem::MaybeUninit::uninit().assume_init()
```

which is UB and [the examples](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html#examples-4) call this out as very definitely incorrect.

**Comment by bwasty** [comment]
Solved by #64
