### ISSUE TITLE
how to remove gltf-viewer

### ISSUE THREAD

**Issue by jmlg10** [bwasty/gltf-viewer#8]
Hello,

I've tried your gltf-viewer to see how it works.

Can you help me to clean uninstall everything ?
I've tried to run a "cargo uninstall gltf-viewer"
but I get aonly a "removing gltf-viewer"

I'm not sure that all the stuff installed with gltf-viewer was also removed.

**Comment by jmlg10** [comment]
I guess that all this stuff:
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing gltf-viewer v0.1.0
   Compiling color_quant v1.0.0
   Compiling dtoa v0.4.2
   Compiling byteorder v1.1.0
   Compiling itoa v0.3.4
   Compiling ansi_term v0.10.2
   Compiling percent-encoding v1.0.1
   Compiling scoped_threadpool v0.1.8
   Compiling cfg-if v0.1.2
   Compiling pkg-config v0.3.9
   Compiling log v0.3.8
   Compiling slab v0.4.0
   Compiling inflections v1.1.1
   Compiling build_const v0.2.0
   Compiling approx v0.1.1
   Compiling httparse v1.2.3
   Compiling futures v0.1.17
   Compiling quote v0.3.15
   Compiling smallvec v0.2.1
   Compiling block v0.1.6
   Compiling rayon-core v1.3.0
   Compiling adler32 v1.0.2
   Compiling slab v0.3.0
   Compiling take v0.1.0
   Compiling inflate v0.2.0
   Compiling unicode-width v0.1.4
   Compiling lzw v0.10.0
   Compiling bitflags v0.9.1
   Compiling core-foundation-sys v0.4.6
   Compiling core-foundation-sys v0.2.3
   Compiling scoped-tls v0.1.0
   Compiling core-foundation-sys v0.3.1
   Compiling num-traits v0.1.40
   Compiling matches v0.1.6
   Compiling version_check v0.1.3
   Compiling unicode-xid v0.0.4
   Compiling security-framework-sys v0.1.16
   Compiling language-tags v0.2.2
   Compiling khronos_api v2.0.0
   Compiling either v1.4.0
   Compiling strsim v0.6.0
   Compiling vec_map v0.8.0
   Compiling safemem v0.2.0
   Compiling lazycell v0.5.1
   Compiling bitflags v1.0.1
   Compiling khronos_api v1.0.1
   Compiling lazy_static v0.2.11
   Compiling term v0.4.6
   Compiling unicode-normalization v0.1.5
   Compiling libc v0.2.33
   Compiling serde v1.0.21
   Compiling scopeguard v0.3.3
   Compiling crc v1.6.0
   Compiling deflate v0.7.17
   Compiling textwrap v0.9.0
   Compiling gif v0.9.2
   Compiling xml-rs v0.6.1
   Compiling tokio-service v0.1.0
   Compiling relay v0.1.0
   Compiling unicode-bidi v0.3.4
   Compiling synom v0.11.3
   Compiling num-integer v0.1.35
   Compiling enum_primitive v0.1.1
   Compiling unicase v2.1.0
   Compiling itertools v0.6.5
   Compiling base64 v0.6.0
   Compiling xml-rs v0.7.0
   Compiling malloc_buf v0.0.6
   Compiling iovec v0.1.1
   Compiling net2 v0.2.31
   Compiling rand v0.3.18
   Compiling time v0.1.38
   Compiling atty v0.2.3
   Compiling shared_library v0.1.7
   Compiling num_cpus v1.7.0
   Compiling coco v0.1.1
   Compiling syn v0.11.11
   Compiling num-rational v0.1.40
   Compiling num-iter v0.1.34
   Compiling idna v0.1.4
   Compiling serde_json v1.0.6
   Compiling objc v0.2.2
   Compiling bytes v0.4.5
   Compiling mio v0.6.11
   Compiling gl_generator v0.5.5
   Compiling clap v2.28.0
   Compiling cgmath v0.14.1
   Compiling tempdir v0.3.5
   Compiling cgmath v0.15.0
   Compiling futures-cpupool v0.1.7
   Compiling simplelog v0.4.3
   Compiling core-foundation v0.2.3
   Compiling core-foundation v0.4.6
   Compiling core-foundation v0.3.0
   Compiling png v0.8.0
   Compiling gl_generator v0.6.1
   Compiling url v1.6.0
   Compiling tokio-io v0.1.4
   Compiling glutin v0.9.2
   Compiling serde_derive_internals v0.17.0
   Compiling gltf-derive v0.9.3
   Compiling libflate v0.1.12
   Compiling security-framework v0.1.16
   Compiling core-graphics v0.8.2
   Compiling rayon v0.8.2
   Compiling mime v0.3.5
   Compiling gleam v0.4.14
   Compiling gl v0.6.5
   Compiling tokio-core v0.1.10
   Compiling serde_urlencoded v0.5.1
   Compiling serde_derive v1.0.21
   Compiling cocoa v0.9.2
   Compiling native-tls v0.1.4
   Compiling jpeg-decoder v0.1.13
   Compiling tokio-proto v0.1.1
   Compiling tokio-tls v0.1.3
   Compiling winit v0.7.6
   Compiling image v0.14.0
   Compiling hyper v0.11.7
   Compiling gltf-json v0.9.3
   Compiling hyper-tls v0.1.2
   Compiling cgl v0.2.1
   Compiling reqwest v0.7.3
   Compiling gltf v0.9.3
   Compiling gltf-utils v0.9.3
   Compiling gltf-importer v0.9.3
   Compiling gltf-viewer v0.1.0
    Finished release [optimized] target(s) in 537.59 secs
may have affected my system.

For information the module
qltf-Quicklook from "magicien" (https://github.com/magicien/GLTFQuickLook), is no more running as good now.
"Reflexion map" and "normal map" don't works anymore.

Have you an idea of what can has been modified?

Thanks

**Comment by bwasty** [comment]
I don't know of a clean way to uninstall dependencies - but their source is cached in `~/.cargo` (on Linux/Mac; not sure about Win), somewhere in the `registry` and `git` subdirectories and is safe to delete. As far as I could find it, the build itself is done in a temporary directory (for a global `cargo install`), so there should be nothing left afterwards.

I have no idea about GLTFQuickLook - that's a completely independent project.

**Comment by jmlg10** [comment]
Ok,

I found this also a little strange, but that's a fact.
Since I have installed and unsinstalled your glTF-viewer app, the plug-in from "magicien" for quicklook don't works any more ( at least the PBR rendering). I'm really confident that your installer  modify something in the system ( high sierra) that is not uninstalled when you uninstall it with cargo...

**Comment by alteous** [comment]
Rust binaries are statically linked AFAIK so it should be sufficient to just remove the binary (`cargo uninstall gltf-viewer`). Removing said binary should have no side effects on your system.

**Comment by jmlg10** [comment]
That's what I've done, but even if Quicklook is running, I've lost the "PBR" rendering

**Comment by bwasty** [comment]
There's hardly any possibility that this viewer could influence the "PBR" rendering of the quicklook plugin (completely different source, dependencies, even shading language).

Also, for me the quicklook plugin works fine - no significant rendering differences to my viewer. Are you sure you are looking at PBR models? Most sample models don't actually have PBR materials - [these](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0#pbr-models) are some that do have them.

**Comment by bwasty** [comment]
Closing this as the Quicklook plugin's author [agrees](https://github.com/magicien/GLTFQuickLook/issues/3#issuecomment-348591540) that there should be no interaction between the two viewers.
