### ISSUE TITLE
Generation of multiple screenshots from different orbital angles.

### ISSUE THREAD

**Issue by siddhartpai** [bwasty/gltf-viewer#9]
Hi @bwasty I was trying to implement multiple screenshot generation on the gltf-viewer similar to the functionality on this tool https://github.com/pycollada/meshtool , and it would be great if I could get some help . 

Thanks

**Comment by bwasty** [comment]
Sure! What have you tried so far?
I guess you're referring to the `--save_rotate_screenshots` param of `meshtool`?

Some pointers about the code:
- I've worked on better camera navigation a while ago, but didn't finish (some weird behaviour that would need more debugging) - see https://github.com/bwasty/gltf-viewer/compare/develop
- the determination of a "nice" initial camera position added in 0.1.0 is rather preliminary, but I didn't get around to improving it yet (see https://github.com/bwasty/gltf-viewer/blob/develop/src/viewer.rs#L208-L236)

**Comment by siddhartpai** [comment]
Yes I'm referring to the same , I'm not sure where to get started on with ,
but I've been reading up your code and trying to understand it. I saw those
commits on the develop branch and forked from that branch itself. I would
need the nice initial camera position to work for my usecase as well .

I added an extra argument `number` when the screenshot parameter is used to
take multiple screenshots. This code works and is capable of taking
multiple screenshots.

Now i need to figure out how to trigger the orbital controls to move around
the object.

I've pushed the code to my github fork
<https://github.com/siddhartpai/gltf-viewer/tree/f/multiscreenshot>.

**Comment by siddhartpai** [comment]
My code is probably going to be dirty , I really don't know what i'm doing
, but I'm hacking my way here .

**Comment by siddhartpai** [comment]
Hi @bwasty I was successful in generating the orbital screenshots at an angle of 6 degrees , between each  screenshot . You can check out the branch at https://github.com/bwasty/gltf-viewer/compare/develop...siddhartpai:f/multiscreenshot  
It would be great if you could give me comments on how I could make the code better or move things around . 

Thanks .

**Comment by bwasty** [comment]
Resolved by #10.
